server:
  port: 8081

authorization:
  url: http://localhost:8080/auth/realms/app-backend/protocol/openid-connect/token

partner:
  url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
